"""add email and full name field on user model

Revision ID: eb37bb343f50
Revises: 0c8f0f473fdc
Create Date: 2025-02-28 21:28:24.834888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb37bb343f50'
down_revision: Union[str, None] = '0c8f0f473fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user_model', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'full_name')
    op.drop_column('user_model', 'email')
    # ### end Alembic commands ###
